---
- hosts: all
  become: true
  become_user: root
  become_method: sudo
  tasks:

# Installing packages: docker-ce, docker-ce-cli, containerd.io and then adding a user named “vagrant” to the “docker” group.
  - name: Install packages that allow apt to be used over HTTPS
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common